export const All_PRODUCT_REQUEST = "All_PRODUCT_REQUEST";
export const All_PRODUCT_SUCCESS = "All_PRODUCT_SUCCESS";
export const All_PRODUCT_FAIL = "All_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PRODUCT_DETAILS_REQUEST = "All_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "All_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "All_DETAILS_FAIL";

