export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

export const REG_USER_REQUEST = "REG_USER_REQUEST"
export const REG_USER_SUCCESS = "REG_USER_SUCCESS"
export const REG_USER_FAIL = "REG_USER_FAIL"




export const CLEAR_ERRORS = "CLEAR_ERRORS";
