export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

export const REG_USER_REQUEST = "REG_USER_REQUEST"
export const REG_USER_SUCCESS = "REG_USER_SUCCESS"
export const REG_USER_FAIL = "REG_USER_FAIL"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS";
